# 第1章 预备知识

## 1.1 数据操作

## 1.1.1 创建Tensor

导入PyTorch

In [ ]:
import torch
print("版本号为：{}".format(torch.__version__))

版本号为：1.1.0


创建行向量

In [ ]:
tensor_a = torch.arange(0, 12)
tensor_a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print("张量的存储位置：{}".format(tensor_a.device))

张量的存储位置：cpu


获取张量的形状

In [ ]:
tensor_a.shape

torch.Size([12])

获取张量中元素总数

In [ ]:
tensor_a.numel()

12

维度变换

In [ ]:
X = tensor_a.view(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
X = tensor_a.view(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
X = tensor_a.view(-1, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

全0张量

In [ ]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

全1张量

In [ ]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

通过列表创建张量

In [ ]:
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

正态分布随机初始化张量的值

In [ ]:
torch.randn((3, 4))

tensor([[ 0.7397, -1.2009,  0.7753, -0.9972],
        [ 1.0678,  1.0227, -0.4779,  0.0222],
        [ 0.7110, -1.4663,  1.5332,  2.0392]])

## 1.1.2 运算

按元素加法

In [ ]:
X + Y

tensor([[ 2,  2,  6,  6],
        [ 5,  7,  9, 11],
        [12, 12, 12, 12]])

按元素乘法

In [ ]:
X * Y

tensor([[ 0,  1,  8,  9],
        [ 4, 10, 18, 28],
        [32, 27, 20, 11]])

按元素除法

In [ ]:
X.float() / Y.float()

tensor([[ 0.0000,  1.0000,  0.5000,  1.0000],
        [ 4.0000,  2.5000,  2.0000,  1.7500],
        [ 2.0000,  3.0000,  5.0000, 11.0000]])

按元素做指数运算

In [ ]:
torch.exp(Y.float())

tensor([[ 7.3891,  2.7183, 54.5981, 20.0855],
        [ 2.7183,  7.3891, 20.0855, 54.5981],
        [54.5981, 20.0855,  7.3891,  2.7183]])

矩阵乘法

In [ ]:
X @ Y.t()

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

纵向拼接与横向拼接

In [ ]:
torch.cat((X, Y), 0), torch.cat((X, Y), 1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

条件判别式

In [ ]:
X == Y

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

张量内元素求和

In [ ]:
torch.sum(X)

tensor(66)

计算结果转换为标量

In [ ]:
torch.norm(X.float()).item()

22.494443893432617

## 1.1.3 广播机制

创建张量

In [ ]:
A = torch.arange(0, 3).view(3, 1)
B = torch.arange(0, 2).view(1, 2)
A, B

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 1.1.4 索引

In [ ]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

修改张量中某位置元素的值

In [ ]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

对部分元素重新赋值

In [ ]:
X[1:2, :] = 12
X

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 1.1.5 运算的内存开销

内存不同

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

内存相同

In [ ]:
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [ ]:
torch.add(X, Y, out=Z)
id(Z) == before

True

In [ ]:
before = id(X)
X += Y
id(X) == before

True

### 1.1.6 Tensor和NumPy相互变换

将NumPy变换为Tensor

In [ ]:
import numpy as np
P = np.ones((2, 3))
D = torch.from_numpy(P)
D

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

将Tensor变换为NumPy

In [ ]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

## 1.2 自动求梯度

In [ ]:
from torch import autograd

### 1.2.1 简单例子

In [ ]:
x = torch.arange(4).float()
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [ ]:
y = 2*torch.dot(x, x.t())

In [ ]:
y.backward()

In [ ]:
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


## 1.3 查阅文档

In [ ]:
print(dir(torch.random))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_fork_rng_warned_already', 'contextlib', 'default_generator', 'fork_rng', 'get_rng_state', 'initial_seed', 'manual_seed', 'set_rng_state', 'warnings']


In [ ]:
help(torch.ones_like)

Help on built-in function ones_like:

ones_like(...)
    ones_like(input, dtype=None, layout=None, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the same size as
    :attr:`input`. ``torch.ones_like(input)`` is equivalent to
    ``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.
    
    .. warning::
        As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
        the old ``torch.ones_like(input, out=output)`` is equivalent to
        ``torch.ones(input.size(), out=output)``.
    
    Args:
        input (Tensor): the size of :attr:`input` will determine size of the output tensor
        dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
            Default: if ``None``, defaults to the dtype of :attr:`input`.
        layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
            Default: 

In [ ]:
x = torch.tensor([[0, 0, 0], [2, 2, 2]])
y = torch.ones_like(x)
y

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.ones_like?

Docstring:
ones_like(input, dtype=None, layout=None, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `1`, with the same size as
:attr:`input`. ``torch.ones_like(input)`` is equivalent to
``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

.. warning::
    As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
    the old ``torch.ones_like(input, out=output)`` is equivalent to
    ``torch.ones(input.size(), out=output)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desire

In [ ]:
torch.ones_like??

Docstring:
ones_like(input, dtype=None, layout=None, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `1`, with the same size as
:attr:`input`. ``torch.ones_like(input)`` is equivalent to
``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

.. warning::
    As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
    the old ``torch.ones_like(input, out=output)`` is equivalent to
    ``torch.ones(input.size(), out=output)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desire